/* automatically generated from xfdesktop-settings-appearance-frame-ui.glade */
#ifdef __SUNPRO_C
#pragma align 4 (xfdesktop_settings_appearance_frame_ui)
#endif
#ifdef __GNUC__
static const char xfdesktop_settings_appearance_frame_ui[] __attribute__ ((__aligned__ (4))) =
#else
static const char xfdesktop_settings_appearance_frame_ui[] =
#endif
{
  "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<!-- Generated with glade 3"
  ".22.1 -->\n<interface>\n  <requires lib=\"gtk+\" version=\"3.20\"/>\n  "
  "<object class=\"GtkAdjustment\" id=\"adjustment3\">\n    <property name"
  "=\"lower\">1</property>\n    <property name=\"upper\">65535</property>\n"
  "    <property name=\"value\">10</property>\n    <property name=\"step_i"
  "ncrement\">1</property>\n    <property name=\"page_increment\">10</prop"
  "erty>\n  </object>\n  <object class=\"GtkListStore\" id=\"model2\">\n  "
  "  <columns>\n      <!-- column-name gchararray -->\n      <column type="
  "\"gchararray\"/>\n    </columns>\n    <data>\n      <row>\n        <col"
  " id=\"0\" translatable=\"yes\">Solid color</col>\n      </row>\n      <"
  "row>\n        <col id=\"0\" translatable=\"yes\">Horizontal gradient</c"
  "ol>\n      </row>\n      <row>\n        <col id=\"0\" translatable=\"ye"
  "s\">Vertical gradient</col>\n      </row>\n      <row>\n        <col id"
  "=\"0\" translatable=\"yes\">Transparent</col>\n      </row>\n    </data"
  ">\n  </object>\n  <object class=\"GtkAlignment\" id=\"alignment_setting"
  "s\">\n    <property name=\"visible\">True</property>\n    <property nam"
  "e=\"can_focus\">False</property>\n    <property name=\"events\">GDK_POI"
  "NTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK"
  " | GDK_BUTTON_RELEASE_MASK</property>\n    <property name=\"border_widt"
  "h\">12</property>\n    <child>\n      <object class=\"GtkBox\" id=\"bac"
  "kground_tab_vbox\">\n        <property name=\"visible\">True</property>"
  "\n        <property name=\"can_focus\">False</property>\n        <prope"
  "rty name=\"orientation\">vertical</property>\n        <property name=\""
  "spacing\">6</property>\n        <child>\n          <object class=\"GtkI"
  "nfoBar\" id=\"infobar_header\">\n            <property name=\"visible\""
  ">True</property>\n            <property name=\"can_focus\">False</prope"
  "rty>\n            <property name=\"events\">GDK_POINTER_MOTION_MASK | G"
  "DK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEAS"
  "E_MASK</property>\n            <child internal-child=\"action_area\">\n"
  "              <object class=\"GtkButtonBox\">\n                <propert"
  "y name=\"can_focus\">False</property>\n              </object>\n       "
  "       <packing>\n                <property name=\"expand\">False</prop"
  "erty>\n                <property name=\"fill\">False</property>\n      "
  "          <property name=\"position\">0</property>\n              </pac"
  "king>\n            </child>\n            <child internal-child=\"conten"
  "t_area\">\n              <object class=\"GtkBox\">\n                <pr"
  "operty name=\"can_focus\">False</property>\n              </object>\n  "
  "            <packing>\n                <property name=\"expand\">False<"
  "/property>\n                <property name=\"fill\">False</property>\n "
  "               <property name=\"position\">0</property>\n              "
  "</packing>\n            </child>\n          </object>\n          <packi"
  "ng>\n            <property name=\"expand\">False</property>\n          "
  "  <property name=\"fill\">True</property>\n            <property name=\""
  "position\">0</property>\n          </packing>\n        </child>\n      "
  "  <child>\n          <object class=\"GtkBox\" id=\"background_tab_hbox\""
  ">\n            <property name=\"visible\">True</property>\n            "
  "<property name=\"can_focus\">False</property>\n            <child>\n   "
  "           <object class=\"GtkLabel\" id=\"label_header\">\n           "
  "     <property name=\"visible\">True</property>\n                <prope"
  "rty name=\"can_focus\">False</property>\n                <property name"
  "=\"events\">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GD"
  "K_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK</property>\n             "
  " </object>\n              <packing>\n                <property name=\"e"
  "xpand\">False</property>\n                <property name=\"fill\">True<"
  "/property>\n                <property name=\"position\">1</property>\n "
  "             </packing>\n            </child>\n          </object>\n   "
  "       <packing>\n            <property name=\"expand\">False</property"
  ">\n            <property name=\"fill\">True</property>\n            <pr"
  "operty name=\"position\">1</property>\n          </packing>\n        </"
  "child>\n        <child>\n          <object class=\"GtkScrolledWindow\" "
  "id=\"iconview_imagelist_scrolled_window\">\n            <property name="
  "\"visible\">True</property>\n            <property name=\"can_focus\">T"
  "rue</property>\n            <property name=\"events\">GDK_POINTER_MOTIO"
  "N_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUT"
  "TON_RELEASE_MASK</property>\n            <property name=\"shadow_type\""
  ">etched-in</property>\n            <child>\n              <object class"
  "=\"GtkIconView\" id=\"iconview_imagelist\">\n                <property "
  "name=\"visible\">True</property>\n                <property name=\"can_"
  "focus\">True</property>\n                <property name=\"events\">GDK_"
  "POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_M"
  "ASK | GDK_BUTTON_RELEASE_MASK</property>\n                <property nam"
  "e=\"margin\">0</property>\n              </object>\n            </child"
  ">\n          </object>\n          <packing>\n            <property name"
  "=\"expand\">True</property>\n            <property name=\"fill\">True</"
  "property>\n            <property name=\"position\">2</property>\n      "
  "    </packing>\n        </child>\n        <child>\n          <object cl"
  "ass=\"GtkGrid\" id=\"folder_color_and_image_style_table\">\n           "
  " <property name=\"visible\">True</property>\n            <property name"
  "=\"can_focus\">False</property>\n            <property name=\"row_spaci"
  "ng\">6</property>\n            <property name=\"column_spacing\">12</pr"
  "operty>\n            <child>\n              <object class=\"GtkFileChoo"
  "serButton\" id=\"btn_folder\">\n                <property name=\"visibl"
  "e\">True</property>\n                <property name=\"can_focus\">True<"
  "/property>\n                <property name=\"events\">GDK_POINTER_MOTIO"
  "N_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUT"
  "TON_RELEASE_MASK</property>\n                <property name=\"tooltip_t"
  "ext\" translatable=\"yes\">Choose the folder to select wallpapers from."
  "</property>\n                <property name=\"hexpand\">True</property>"
  "\n                <property name=\"action\">select-folder</property>\n "
  "             </object>\n              <packing>\n                <prope"
  "rty name=\"left_attach\">1</property>\n                <property name=\""
  "top_attach\">0</property>\n              </packing>\n            </chil"
  "d>\n            <child>\n              <object class=\"GtkAlignment\" i"
  "d=\"alignment_spacer\">\n                <property name=\"visible\">Tru"
  "e</property>\n                <property name=\"can_focus\">False</prope"
  "rty>\n                <property name=\"hexpand\">True</property>\n     "
  "         </object>\n              <packing>\n                <property "
  "name=\"left_attach\">4</property>\n                <property name=\"top"
  "_attach\">0</property>\n              </packing>\n            </child>\n"
  "            <child>\n              <object class=\"GtkLabel\" id=\"labe"
  "l_style\">\n                <property name=\"visible\">True</property>\n"
  "                <property name=\"can_focus\">False</property>\n        "
  "        <property name=\"events\">GDK_POINTER_MOTION_MASK | GDK_POINTER"
  "_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK</pr"
  "operty>\n                <property name=\"label\" translatable=\"yes\">"
  "St_yle:</property>\n                <property name=\"use_underline\">Tr"
  "ue</property>\n                <property name=\"mnemonic_widget\">combo"
  "_style</property>\n                <property name=\"xalign\">0</propert"
  "y>\n              </object>\n              <packing>\n                <"
  "property name=\"left_attach\">5</property>\n                <property n"
  "ame=\"top_attach\">0</property>\n              </packing>\n            "
  "</child>\n            <child>\n              <object class=\"GtkComboBo"
  "xText\" id=\"combo_style\">\n                <property name=\"visible\""
  ">True</property>\n                <property name=\"can_focus\">False</p"
  "roperty>\n                <property name=\"events\">GDK_POINTER_MOTION_"
  "MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTO"
  "N_RELEASE_MASK</property>\n                <property name=\"tooltip_tex"
  "t\" translatable=\"yes\">Specify how the image will be resized to fit t"
  "he screen.</property>\n                <items>\n                  <item"
  " translatable=\"yes\">None</item>\n                  <item translatable"
  "=\"yes\">Centered</item>\n                  <item translatable=\"yes\">"
  "Tiled</item>\n                  <item translatable=\"yes\">Stretched</i"
  "tem>\n                  <item translatable=\"yes\">Scaled</item>\n     "
  "             <item translatable=\"yes\">Zoomed</item>\n                "
  "  <item translatable=\"yes\">Spanning Screens</item>\n                <"
  "/items>\n              </object>\n              <packing>\n            "
  "    <property name=\"left_attach\">6</property>\n                <prope"
  "rty name=\"top_attach\">0</property>\n              </packing>\n       "
  "     </child>\n            <child>\n              <object class=\"GtkCo"
  "mboBox\" id=\"combo_colors\">\n                <property name=\"visible"
  "\">True</property>\n                <property name=\"can_focus\">False<"
  "/property>\n                <property name=\"events\">GDK_POINTER_MOTIO"
  "N_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUT"
  "TON_RELEASE_MASK</property>\n                <property name=\"tooltip_t"
  "ext\" translatable=\"yes\">Specify the style of the color drawn behind "
  "the backdrop image.</property>\n                <property name=\"valign"
  "\">center</property>\n                <property name=\"hexpand\">True</"
  "property>\n                <property name=\"model\">model2</property>\n"
  "                <child>\n                  <object class=\"GtkCellRende"
  "rerText\" id=\"renderer2\"/>\n                  <attributes>\n         "
  "           <attribute name=\"text\">0</attribute>\n                  </"
  "attributes>\n                </child>\n              </object>\n       "
  "       <packing>\n                <property name=\"left_attach\">1</pro"
  "perty>\n                <property name=\"top_attach\">1</property>\n   "
  "           </packing>\n            </child>\n            <child>\n     "
  "         <object class=\"GtkColorButton\" id=\"color1_btn\">\n         "
  "       <property name=\"visible\">True</property>\n                <pro"
  "perty name=\"can_focus\">True</property>\n                <property nam"
  "e=\"receives_default\">True</property>\n                <property name="
  "\"events\">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK"
  "_BUTTON_MOTION_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK</"
  "property>\n                <property name=\"tooltip_text\" translatable"
  "=\"yes\">Specifies the solid color, or the \"left\" or \"top\" color of"
  " the gradient.</property>\n                <property name=\"title\" tra"
  "nslatable=\"yes\">Select First Color</property>\n              </object"
  ">\n              <packing>\n                <property name=\"left_attac"
  "h\">2</property>\n                <property name=\"top_attach\">1</prop"
  "erty>\n              </packing>\n            </child>\n            <chi"
  "ld>\n              <object class=\"GtkColorButton\" id=\"color2_btn\">\n"
  "                <property name=\"visible\">True</property>\n           "
  "     <property name=\"can_focus\">True</property>\n                <pro"
  "perty name=\"receives_default\">True</property>\n                <prope"
  "rty name=\"events\">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_M"
  "ASK | GDK_BUTTON_MOTION_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEA"
  "SE_MASK</property>\n                <property name=\"tooltip_text\" tra"
  "nslatable=\"yes\">Specifies the \"right\" or \"bottom\" color of the gr"
  "adient.</property>\n                <property name=\"title\" translatab"
  "le=\"yes\">Select Second Color</property>\n              </object>\n   "
  "           <packing>\n                <property name=\"left_attach\">3<"
  "/property>\n                <property name=\"top_attach\">1</property>\n"
  "              </packing>\n            </child>\n            <child>\n  "
  "            <object class=\"GtkCheckButton\" id=\"chk_apply_to_all\">\n"
  "                <property name=\"label\" translatable=\"yes\">Apply to "
  "all _workspaces</property>\n                <property name=\"visible\">"
  "True</property>\n                <property name=\"can_focus\">True</pro"
  "perty>\n                <property name=\"receives_default\">False</prop"
  "erty>\n                <property name=\"events\">GDK_POINTER_MOTION_MAS"
  "K | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_R"
  "ELEASE_MASK</property>\n                <property name=\"use_underline\""
  ">True</property>\n                <property name=\"draw_indicator\">Tru"
  "e</property>\n              </object>\n              <packing>\n       "
  "         <property name=\"left_attach\">6</property>\n                <"
  "property name=\"top_attach\">1</property>\n              </packing>\n  "
  "          </child>\n            <child>\n              <object class=\""
  "GtkLabel\" id=\"label_folder\">\n                <property name=\"visib"
  "le\">True</property>\n                <property name=\"can_focus\">Fals"
  "e</property>\n                <property name=\"events\">GDK_POINTER_MOT"
  "ION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK_B"
  "UTTON_RELEASE_MASK</property>\n                <property name=\"label\""
  " translatable=\"yes\">_Folder:</property>\n                <property na"
  "me=\"use_underline\">True</property>\n                <property name=\""
  "mnemonic_widget\">btn_folder</property>\n                <property name"
  "=\"xalign\">0</property>\n              </object>\n              <packi"
  "ng>\n                <property name=\"left_attach\">0</property>\n     "
  "           <property name=\"top_attach\">0</property>\n              </"
  "packing>\n            </child>\n            <child>\n              <obj"
  "ect class=\"GtkLabel\" id=\"label_color\">\n                <property n"
  "ame=\"visible\">True</property>\n                <property name=\"can_f"
  "ocus\">False</property>\n                <property name=\"events\">GDK_"
  "POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_M"
  "ASK | GDK_BUTTON_RELEASE_MASK</property>\n                <property nam"
  "e=\"label\" translatable=\"yes\">C_olor:</property>\n                <p"
  "roperty name=\"use_underline\">True</property>\n                <proper"
  "ty name=\"mnemonic_widget\">combo_colors</property>\n                <p"
  "roperty name=\"xalign\">0</property>\n              </object>\n        "
  "      <packing>\n                <property name=\"left_attach\">0</prop"
  "erty>\n                <property name=\"top_attach\">1</property>\n    "
  "          </packing>\n            </child>\n            <child>\n      "
  "        <placeholder/>\n            </child>\n            <child>\n    "
  "          <placeholder/>\n            </child>\n            <child>\n  "
  "            <placeholder/>\n            </child>\n            <child>\n"
  "              <placeholder/>\n            </child>\n          </object>"
  "\n          <packing>\n            <property name=\"expand\">False</pro"
  "perty>\n            <property name=\"fill\">True</property>\n          "
  "  <property name=\"position\">3</property>\n          </packing>\n     "
  "   </child>\n        <child>\n          <object class=\"GtkBox\" id=\"c"
  "ycle_options_hbox\">\n            <property name=\"visible\">True</prop"
  "erty>\n            <property name=\"can_focus\">False</property>\n     "
  "       <property name=\"events\">GDK_POINTER_MOTION_MASK | GDK_POINTER_"
  "MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK</pro"
  "perty>\n            <property name=\"spacing\">12</property>\n         "
  "   <child>\n              <object class=\"GtkCheckButton\" id=\"chk_cyc"
  "le_backdrop\">\n                <property name=\"label\" translatable=\""
  "yes\">Change the _background </property>\n                <property nam"
  "e=\"visible\">True</property>\n                <property name=\"can_foc"
  "us\">True</property>\n                <property name=\"receives_default"
  "\">False</property>\n                <property name=\"events\">GDK_POIN"
  "TER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK "
  "| GDK_BUTTON_RELEASE_MASK</property>\n                <property name=\""
  "tooltip_text\" translatable=\"yes\">Automatically select a different ba"
  "ckground from the current directory.</property>\n                <prope"
  "rty name=\"use_underline\">True</property>\n                <property n"
  "ame=\"draw_indicator\">True</property>\n              </object>\n      "
  "        <packing>\n                <property name=\"expand\">False</pro"
  "perty>\n                <property name=\"fill\">True</property>\n      "
  "          <property name=\"position\">0</property>\n              </pac"
  "king>\n            </child>\n            <child>\n              <object"
  " class=\"GtkComboBoxText\" id=\"combo_cycle_backdrop_period\">\n       "
  "         <property name=\"visible\">True</property>\n                <p"
  "roperty name=\"sensitive\">False</property>\n                <property "
  "name=\"can_focus\">False</property>\n                <property name=\"e"
  "vents\">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BU"
  "TTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK</property>\n                <"
  "property name=\"tooltip_text\" translatable=\"yes\">Specify how often t"
  "he background will change.</property>\n                <items>\n       "
  "           <item translatable=\"yes\">in seconds:</item>\n             "
  "     <item translatable=\"yes\">in minutes:</item>\n                  <"
  "item translatable=\"yes\">in hours:</item>\n                  <item tra"
  "nslatable=\"yes\">at start up</item>\n                  <item translata"
  "ble=\"yes\">every hour</item>\n                  <item translatable=\"y"
  "es\">every day</item>\n                  <item translatable=\"yes\">chr"
  "onologically</item>\n                </items>\n              </object>\n"
  "              <packing>\n                <property name=\"expand\">Fals"
  "e</property>\n                <property name=\"fill\">True</property>\n"
  "                <property name=\"position\">1</property>\n             "
  " </packing>\n            </child>\n            <child>\n              <"
  "object class=\"GtkSpinButton\" id=\"spin_backdrop_time\">\n            "
  "    <property name=\"visible\">True</property>\n                <proper"
  "ty name=\"sensitive\">False</property>\n                <property name="
  "\"can_focus\">True</property>\n                <property name=\"events\""
  ">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PR"
  "ESS_MASK | GDK_BUTTON_RELEASE_MASK</property>\n                <propert"
  "y name=\"tooltip_text\" translatable=\"yes\">Amount of time before a di"
  "fferent background is selected.</property>\n                <property n"
  "ame=\"adjustment\">adjustment3</property>\n              </object>\n   "
  "           <packing>\n                <property name=\"expand\">False</"
  "property>\n                <property name=\"fill\">True</property>\n   "
  "             <property name=\"position\">2</property>\n              </"
  "packing>\n            </child>\n            <child>\n              <obj"
  "ect class=\"GtkCheckButton\" id=\"chk_random_backdrop_order\">\n       "
  "         <property name=\"label\" translatable=\"yes\">_Random Order</p"
  "roperty>\n                <property name=\"visible\">True</property>\n "
  "               <property name=\"sensitive\">False</property>\n         "
  "       <property name=\"can_focus\">True</property>\n                <p"
  "roperty name=\"receives_default\">False</property>\n                <pr"
  "operty name=\"events\">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HIN"
  "T_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK</property>\n  "
  "              <property name=\"tooltip_text\" translatable=\"yes\">Rand"
  "omly selects another image from the same directory when the wallpaper i"
  "s to cycle.</property>\n                <property name=\"use_underline\""
  ">True</property>\n                <property name=\"draw_indicator\">Tru"
  "e</property>\n              </object>\n              <packing>\n       "
  "         <property name=\"expand\">False</property>\n                <p"
  "roperty name=\"fill\">True</property>\n                <property name=\""
  "position\">3</property>\n              </packing>\n            </child>"
  "\n          </object>\n          <packing>\n            <property name="
  "\"expand\">False</property>\n            <property name=\"fill\">True</"
  "property>\n            <property name=\"position\">5</property>\n      "
  "    </packing>\n        </child>\n      </object>\n    </child>\n  </ob"
  "ject>\n</interface>\n"
};

static const unsigned xfdesktop_settings_appearance_frame_ui_length = 19590u;

