/* automatically generated from xfdesktop-settings-ui.glade */
#ifdef __SUNPRO_C
#pragma align 4 (xfdesktop_settings_ui)
#endif
#ifdef __GNUC__
static const char xfdesktop_settings_ui[] __attribute__ ((__aligned__ (4))) =
#else
static const char xfdesktop_settings_ui[] =
#endif
{
  "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<!-- Generated with glade 3"
  ".22.1 -->\n<interface>\n  <requires lib=\"gtk+\" version=\"3.20\"/>\n  "
  "<requires lib=\"libxfce4ui-2\" version=\"4.12\"/>\n  <object class=\"Gt"
  "kAdjustment\" id=\"adjustment3\">\n    <property name=\"lower\">16</pro"
  "perty>\n    <property name=\"upper\">192</property>\n    <property name"
  "=\"value\">48</property>\n    <property name=\"step_increment\">2</prop"
  "erty>\n    <property name=\"page_increment\">10</property>\n  </object>"
  "\n  <object class=\"GtkAdjustment\" id=\"adjustment4\">\n    <property "
  "name=\"upper\">144</property>\n    <property name=\"value\">12</propert"
  "y>\n    <property name=\"step_increment\">1</property>\n    <property n"
  "ame=\"page_increment\">10</property>\n  </object>\n  <object class=\"Gt"
  "kAdjustment\" id=\"adjustment_tooltip\">\n    <property name=\"upper\">"
  "256</property>\n    <property name=\"value\">128</property>\n    <prope"
  "rty name=\"step_increment\">2</property>\n    <property name=\"page_inc"
  "rement\">10</property>\n  </object>\n  <object class=\"GtkImage\" id=\""
  "image1\">\n    <property name=\"visible\">True</property>\n    <propert"
  "y name=\"can_focus\">False</property>\n    <property name=\"icon_name\""
  ">window-close-symbolic</property>\n  </object>\n  <object class=\"GtkIm"
  "age\" id=\"image2\">\n    <property name=\"visible\">True</property>\n "
  "   <property name=\"can_focus\">False</property>\n    <property name=\""
  "icon_name\">help-browser</property>\n  </object>\n  <object class=\"Gtk"
  "ListStore\" id=\"model3\">\n    <columns>\n      <!-- column-name gchar"
  "array -->\n      <column type=\"gchararray\"/>\n    </columns>\n    <da"
  "ta>\n      <row>\n        <col id=\"0\" translatable=\"yes\">Left</col>"
  "\n      </row>\n      <row>\n        <col id=\"0\" translatable=\"yes\""
  ">Middle</col>\n      </row>\n      <row>\n        <col id=\"0\" transla"
  "table=\"yes\">Right</col>\n      </row>\n    </data>\n  </object>\n  <o"
  "bject class=\"GtkListStore\" id=\"model4\">\n    <columns>\n      <!-- "
  "column-name gchararray -->\n      <column type=\"gchararray\"/>\n    </"
  "columns>\n    <data>\n      <row>\n        <col id=\"0\" translatable=\""
  "yes\">None</col>\n      </row>\n      <row>\n        <col id=\"0\" tran"
  "slatable=\"yes\">Shift</col>\n      </row>\n      <row>\n        <col i"
  "d=\"0\" translatable=\"yes\">Alt</col>\n      </row>\n      <row>\n    "
  "    <col id=\"0\" translatable=\"yes\">Control</col>\n      </row>\n   "
  " </data>\n  </object>\n  <object class=\"GtkListStore\" id=\"model5\">\n"
  "    <columns>\n      <!-- column-name gchararray -->\n      <column typ"
  "e=\"gchararray\"/>\n    </columns>\n    <data>\n      <row>\n        <c"
  "ol id=\"0\" translatable=\"yes\">Left</col>\n      </row>\n      <row>\n"
  "        <col id=\"0\" translatable=\"yes\">Middle</col>\n      </row>\n"
  "      <row>\n        <col id=\"0\" translatable=\"yes\">Right</col>\n  "
  "    </row>\n    </data>\n  </object>\n  <object class=\"GtkListStore\" "
  "id=\"model6\">\n    <columns>\n      <!-- column-name gchararray -->\n "
  "     <column type=\"gchararray\"/>\n    </columns>\n    <data>\n      <"
  "row>\n        <col id=\"0\" translatable=\"yes\">None</col>\n      </ro"
  "w>\n      <row>\n        <col id=\"0\" translatable=\"yes\">Shift</col>"
  "\n      </row>\n      <row>\n        <col id=\"0\" translatable=\"yes\""
  ">Alt</col>\n      </row>\n      <row>\n        <col id=\"0\" translatab"
  "le=\"yes\">Control</col>\n      </row>\n    </data>\n  </object>\n  <ob"
  "ject class=\"GtkListStore\" id=\"model7\">\n    <columns>\n      <!-- c"
  "olumn-name gchararray -->\n      <column type=\"gchararray\"/>\n    </c"
  "olumns>\n    <data>\n      <row>\n        <col id=\"0\" translatable=\""
  "yes\">None</col>\n      </row>\n      <row>\n        <col id=\"0\" tran"
  "slatable=\"yes\">Minimized application icons</col>\n      </row>\n     "
  " <row>\n        <col id=\"0\" translatable=\"yes\">File/launcher icons<"
  "/col>\n      </row>\n    </data>\n  </object>\n  <object class=\"GtkLis"
  "tStore\" id=\"model8\">\n    <columns>\n      <!-- column-name gchararr"
  "ay -->\n      <column type=\"gchararray\"/>\n    </columns>\n    <data>"
  "\n      <row>\n        <col id=\"0\" translatable=\"yes\">Top Left Vert"
  "ical</col>\n      </row>\n      <row>\n        <col id=\"0\" translatab"
  "le=\"yes\">Top Left Horizontal</col>\n      </row>\n      <row>\n      "
  "  <col id=\"0\" translatable=\"yes\">Top Right Vertical</col>\n      </"
  "row>\n      <row>\n        <col id=\"0\" translatable=\"yes\">Top Right"
  " Horizontal</col>\n      </row>\n      <row>\n        <col id=\"0\" tra"
  "nslatable=\"yes\">Bottom Left Vertical</col>\n      </row>\n      <row>"
  "\n        <col id=\"0\" translatable=\"yes\">Bottom Left Horizontal</co"
  "l>\n      </row>\n      <row>\n        <col id=\"0\" translatable=\"yes"
  "\">Bottom Right Vertical</col>\n      </row>\n      <row>\n        <col"
  " id=\"0\" translatable=\"yes\">Bottom Right Horizontal</col>\n      </r"
  "ow>\n    </data>\n  </object>\n  <object class=\"XfceTitledDialog\" id="
  "\"prefs_dialog\">\n    <property name=\"can_focus\">False</property>\n "
  "   <property name=\"events\">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTI"
  "ON_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK</propert"
  "y>\n    <property name=\"title\" translatable=\"yes\">Desktop</property"
  ">\n    <property name=\"window_position\">center-on-parent</property>\n"
  "    <property name=\"default_width\">640</property>\n    <property name"
  "=\"default_height\">480</property>\n    <property name=\"icon_name\">or"
  "g.xfce.xfdesktop</property>\n    <child internal-child=\"vbox\">\n     "
  " <object class=\"GtkBox\" id=\"dialog-vbox1\">\n        <property name="
  "\"visible\">True</property>\n        <property name=\"can_focus\">False"
  "</property>\n        <property name=\"events\">GDK_POINTER_MOTION_MASK "
  "| GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_REL"
  "EASE_MASK</property>\n        <property name=\"orientation\">vertical</"
  "property>\n        <property name=\"spacing\">2</property>\n        <ch"
  "ild internal-child=\"action_area\">\n          <object class=\"GtkButto"
  "nBox\" id=\"dialog-action_area1\">\n            <property name=\"visibl"
  "e\">True</property>\n            <property name=\"can_focus\">False</pr"
  "operty>\n            <property name=\"events\">GDK_POINTER_MOTION_MASK "
  "| GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_REL"
  "EASE_MASK</property>\n            <child>\n              <object class="
  "\"GtkButton\" id=\"button2\">\n                <property name=\"label\""
  " translatable=\"yes\">_Help</property>\n                <property name="
  "\"visible\">True</property>\n                <property name=\"can_focus"
  "\">True</property>\n                <property name=\"receives_default\""
  ">True</property>\n                <property name=\"events\">GDK_POINTER"
  "_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK | G"
  "DK_BUTTON_RELEASE_MASK</property>\n                <property name=\"ima"
  "ge\">image2</property>\n                <property name=\"use_underline\""
  ">True</property>\n              </object>\n              <packing>\n   "
  "             <property name=\"expand\">True</property>\n               "
  " <property name=\"fill\">True</property>\n                <property nam"
  "e=\"position\">0</property>\n              </packing>\n            </ch"
  "ild>\n            <child>\n              <object class=\"GtkButton\" id"
  "=\"bnt_exit\">\n                <property name=\"label\" translatable=\""
  "yes\">_Close</property>\n                <property name=\"visible\">Tru"
  "e</property>\n                <property name=\"can_focus\">True</proper"
  "ty>\n                <property name=\"receives_default\">True</property"
  ">\n                <property name=\"events\">GDK_POINTER_MOTION_MASK | "
  "GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEA"
  "SE_MASK</property>\n                <property name=\"image\">image1</pr"
  "operty>\n                <property name=\"use_underline\">True</propert"
  "y>\n              </object>\n              <packing>\n                <"
  "property name=\"expand\">True</property>\n                <property nam"
  "e=\"fill\">True</property>\n                <property name=\"position\""
  ">1</property>\n              </packing>\n            </child>\n        "
  "  </object>\n          <packing>\n            <property name=\"expand\""
  ">False</property>\n            <property name=\"fill\">False</property>"
  "\n            <property name=\"pack_type\">end</property>\n            "
  "<property name=\"position\">0</property>\n          </packing>\n       "
  " </child>\n        <child>\n          <object class=\"GtkAlignment\" id"
  "=\"alignment1\">\n            <property name=\"visible\">True</property"
  ">\n            <property name=\"can_focus\">False</property>\n         "
  "   <property name=\"vexpand\">True</property>\n            <child>\n   "
  "           <object class=\"GtkNotebook\" id=\"notebook_settings\">\n   "
  "             <property name=\"visible\">True</property>\n              "
  "  <property name=\"can_focus\">True</property>\n                <proper"
  "ty name=\"events\">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MA"
  "SK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK</property>\n      "
  "          <property name=\"border_width\">6</property>\n               "
  " <child>\n                  <object class=\"GtkNotebook\" id=\"notebook"
  "_screens\">\n                    <property name=\"visible\">True</prope"
  "rty>\n                    <property name=\"can_focus\">True</property>\n"
  "                    <property name=\"show_border\">False</property>\n  "
  "                </object>\n                </child>\n                <c"
  "hild type=\"tab\">\n                  <object class=\"GtkLabel\" id=\"l"
  "abel1\">\n                    <property name=\"visible\">True</property"
  ">\n                    <property name=\"can_focus\">False</property>\n "
  "                   <property name=\"events\">GDK_POINTER_MOTION_MASK | "
  "GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEA"
  "SE_MASK</property>\n                    <property name=\"label\" transl"
  "atable=\"yes\">_Background</property>\n                    <property na"
  "me=\"use_underline\">True</property>\n                  </object>\n    "
  "              <packing>\n                    <property name=\"tab_fill\""
  ">False</property>\n                  </packing>\n                </chil"
  "d>\n                <child>\n                  <object class=\"GtkBox\""
  " id=\"vbox4\">\n                    <property name=\"visible\">True</pr"
  "operty>\n                    <property name=\"can_focus\">False</proper"
  "ty>\n                    <property name=\"events\">GDK_POINTER_MOTION_M"
  "ASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON"
  "_RELEASE_MASK</property>\n                    <property name=\"border_w"
  "idth\">12</property>\n                    <property name=\"orientation\""
  ">vertical</property>\n                    <property name=\"spacing\">18"
  "</property>\n                    <child>\n                      <object"
  " class=\"GtkFrame\" id=\"frame4\">\n                        <property n"
  "ame=\"visible\">True</property>\n                        <property name"
  "=\"can_focus\">False</property>\n                        <property name"
  "=\"events\">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GD"
  "K_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK</property>\n             "
  "           <property name=\"label_xalign\">0</property>\n              "
  "          <property name=\"shadow_type\">none</property>\n             "
  "           <child>\n                          <object class=\"GtkAlignm"
  "ent\" id=\"alignment5\">\n                            <property name=\""
  "visible\">True</property>\n                            <property name=\""
  "can_focus\">False</property>\n                            <property nam"
  "e=\"events\">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | G"
  "DK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK</property>\n            "
  "                <property name=\"top_padding\">6</property>\n          "
  "                  <property name=\"left_padding\">12</property>\n      "
  "                      <child>\n                              <object cl"
  "ass=\"GtkBox\" id=\"vbox7\">\n                                <property"
  " name=\"visible\">True</property>\n                                <pro"
  "perty name=\"can_focus\">False</property>\n                            "
  "    <property name=\"events\">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOT"
  "ION_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK</proper"
  "ty>\n                                <property name=\"orientation\">ver"
  "tical</property>\n                                <property name=\"spac"
  "ing\">6</property>\n                                <child>\n          "
  "                        <object class=\"GtkCheckButton\" id=\"chk_show_"
  "desktop_menu\">\n                                    <property name=\"l"
  "abel\" translatable=\"yes\">Include applications menu on _desktop right"
  " click</property>\n                                    <property name=\""
  "visible\">True</property>\n                                    <propert"
  "y name=\"can_focus\">True</property>\n                                 "
  "   <property name=\"receives_default\">False</property>\n              "
  "                      <property name=\"events\">GDK_POINTER_MOTION_MASK"
  " | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RE"
  "LEASE_MASK</property>\n                                    <property na"
  "me=\"use_underline\">True</property>\n                                 "
  "   <property name=\"active\">True</property>\n                         "
  "           <property name=\"draw_indicator\">True</property>\n         "
  "                         </object>\n                                  <"
  "packing>\n                                    <property name=\"expand\""
  ">True</property>\n                                    <property name=\""
  "fill\">True</property>\n                                    <property n"
  "ame=\"position\">0</property>\n                                  </pack"
  "ing>\n                                </child>\n                       "
  "         <child>\n                                  <object class=\"Gtk"
  "Alignment\" id=\"box_menu_subopts\">\n                                 "
  "   <property name=\"visible\">True</property>\n                        "
  "            <property name=\"can_focus\">False</property>\n            "
  "                        <property name=\"events\">GDK_POINTER_MOTION_MA"
  "SK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_"
  "RELEASE_MASK</property>\n                                    <property "
  "name=\"left_padding\">12</property>\n                                  "
  "  <child>\n                                      <object class=\"GtkBox"
  "\" id=\"vbox10\">\n                                        <property na"
  "me=\"visible\">True</property>\n                                       "
  " <property name=\"can_focus\">False</property>\n                       "
  "                 <property name=\"events\">GDK_POINTER_MOTION_MASK | GD"
  "K_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE"
  "_MASK</property>\n                                        <property nam"
  "e=\"orientation\">vertical</property>\n                                "
  "        <property name=\"spacing\">6</property>\n                      "
  "                  <child>\n                                          <o"
  "bject class=\"GtkBox\" id=\"hbox11\">\n                                "
  "            <property name=\"can_focus\">False</property>\n            "
  "                                <property name=\"events\">GDK_POINTER_M"
  "OTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK"
  "_BUTTON_RELEASE_MASK</property>\n                                      "
  "      <property name=\"spacing\">12</property>\n                       "
  "                     <child>\n                                         "
  "     <object class=\"GtkLabel\" id=\"label17\">\n                      "
  "                          <property name=\"visible\">True</property>\n "
  "                                               <property name=\"can_foc"
  "us\">False</property>\n                                                "
  "<property name=\"events\">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_"
  "HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK</property>\n"
  "                                                <property name=\"label\""
  " translatable=\"yes\">_Button:</property>\n                            "
  "                    <property name=\"use_underline\">True</property>\n "
  "                                               <property name=\"mnemoni"
  "c_widget\">combobox1</property>\n                                      "
  "        </object>\n                                              <packi"
  "ng>\n                                                <property name=\"e"
  "xpand\">False</property>\n                                             "
  "   <property name=\"fill\">True</property>\n                           "
  "                     <property name=\"position\">0</property>\n        "
  "                                      </packing>\n                     "
  "                       </child>\n                                      "
  "      <child>\n                                              <object cl"
  "ass=\"GtkComboBox\" id=\"combobox1\">\n                                "
  "                <property name=\"visible\">True</property>\n           "
  "                                     <property name=\"can_focus\">False"
  "</property>\n                                                <property "
  "name=\"events\">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK "
  "| GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK</property>\n         "
  "                                       <property name=\"model\">model3<"
  "/property>\n                                                <child>\n  "
  "                                                <object class=\"GtkCell"
  "RendererText\" id=\"renderer3\"/>\n                                    "
  "              <attributes>\n                                           "
  "         <attribute name=\"text\">0</attribute>\n                      "
  "                            </attributes>\n                            "
  "                    </child>\n                                         "
  "     </object>\n                                              <packing>"
  "\n                                                <property name=\"expa"
  "nd\">False</property>\n                                                "
  "<property name=\"fill\">True</property>\n                              "
  "                  <property name=\"position\">1</property>\n           "
  "                                   </packing>\n                        "
  "                    </child>\n                                         "
  "   <child>\n                                              <object class"
  "=\"GtkLabel\" id=\"label18\">\n                                        "
  "        <property name=\"visible\">True</property>\n                   "
  "                             <property name=\"can_focus\">False</proper"
  "ty>\n                                                <property name=\"e"
  "vents\">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BU"
  "TTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK</property>\n                 "
  "                               <property name=\"label\" translatable=\""
  "yes\">Mo_difier:</property>\n                                          "
  "      <property name=\"use_underline\">True</property>\n               "
  "                                 <property name=\"mnemonic_widget\">com"
  "bobox2</property>\n                                              </obje"
  "ct>\n                                              <packing>\n         "
  "                                       <property name=\"expand\">False<"
  "/property>\n                                                <property n"
  "ame=\"fill\">True</property>\n                                         "
  "       <property name=\"position\">2</property>\n                      "
  "                        </packing>\n                                   "
  "         </child>\n                                            <child>\n"
  "                                              <object class=\"GtkComboB"
  "ox\" id=\"combobox2\">\n                                               "
  " <property name=\"visible\">True</property>\n                          "
  "                      <property name=\"can_focus\">False</property>\n  "
  "                                              <property name=\"events\""
  ">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PR"
  "ESS_MASK | GDK_BUTTON_RELEASE_MASK</property>\n                        "
  "                        <property name=\"model\">model4</property>\n   "
  "                                             <child>\n                 "
  "                                 <object class=\"GtkCellRendererText\" "
  "id=\"renderer4\"/>\n                                                  <"
  "attributes>\n                                                    <attri"
  "bute name=\"text\">0</attribute>\n                                     "
  "             </attributes>\n                                           "
  "     </child>\n                                              </object>\n"
  "                                              <packing>\n              "
  "                                  <property name=\"expand\">False</prop"
  "erty>\n                                                <property name=\""
  "fill\">True</property>\n                                               "
  " <property name=\"position\">3</property>\n                            "
  "                  </packing>\n                                         "
  "   </child>\n                                          </object>\n     "
  "                                     <packing>\n                       "
  "                     <property name=\"expand\">True</property>\n       "
  "                                     <property name=\"fill\">True</prop"
  "erty>\n                                            <property name=\"pos"
  "ition\">0</property>\n                                          </packi"
  "ng>\n                                        </child>\n                "
  "                        <child>\n                                      "
  "    <object class=\"GtkCheckButton\" id=\"chk_menu_show_app_icons\">\n "
  "                                           <property name=\"label\" tra"
  "nslatable=\"yes\">Show _application icons in menu</property>\n         "
  "                                   <property name=\"visible\">True</pro"
  "perty>\n                                            <property name=\"ca"
  "n_focus\">True</property>\n                                            "
  "<property name=\"receives_default\">False</property>\n                 "
  "                           <property name=\"events\">GDK_POINTER_MOTION"
  "_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTT"
  "ON_RELEASE_MASK</property>\n                                           "
  " <property name=\"use_underline\">True</property>\n                    "
  "                        <property name=\"active\">True</property>\n    "
  "                                        <property name=\"draw_indicator"
  "\">True</property>\n                                          </object>"
  "\n                                          <packing>\n                "
  "                            <property name=\"expand\">True</property>\n"
  "                                            <property name=\"fill\">Tru"
  "e</property>\n                                            <property nam"
  "e=\"position\">1</property>\n                                          "
  "</packing>\n                                        </child>\n         "
  "                               <child>\n                               "
  "           <object class=\"GtkBox\" id=\"hbox12\">\n                   "
  "                         <property name=\"can_focus\">False</property>\n"
  "                                            <property name=\"events\">G"
  "DK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRES"
  "S_MASK | GDK_BUTTON_RELEASE_MASK</property>\n                          "
  "                  <property name=\"spacing\">12</property>\n           "
  "                                 <child>\n                             "
  "                 <object class=\"GtkButton\" id=\"button5\">\n         "
  "                                       <property name=\"label\" transla"
  "table=\"yes\">_Edit desktop menu</property>\n                          "
  "                      <property name=\"visible\">True</property>\n     "
  "                                           <property name=\"can_focus\""
  ">True</property>\n                                                <prop"
  "erty name=\"receives_default\">True</property>\n                       "
  "                         <property name=\"events\">GDK_POINTER_MOTION_M"
  "ASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON"
  "_RELEASE_MASK</property>\n                                             "
  "   <property name=\"use_underline\">True</property>\n                  "
  "                            </object>\n                                "
  "              <packing>\n                                              "
  "  <property name=\"expand\">False</property>\n                         "
  "                       <property name=\"fill\">True</property>\n       "
  "                                         <property name=\"position\">0<"
  "/property>\n                                              </packing>\n "
  "                                           </child>\n                  "
  "                        </object>\n                                    "
  "      <packing>\n                                            <property "
  "name=\"expand\">True</property>\n                                      "
  "      <property name=\"fill\">True</property>\n                        "
  "                    <property name=\"position\">2</property>\n         "
  "                                 </packing>\n                          "
  "              </child>\n                                      </object>"
  "\n                                    </child>\n                       "
  "           </object>\n                                  <packing>\n    "
  "                                <property name=\"expand\">True</propert"
  "y>\n                                    <property name=\"fill\">True</p"
  "roperty>\n                                    <property name=\"position"
  "\">1</property>\n                                  </packing>\n        "
  "                        </child>\n                              </objec"
  "t>\n                            </child>\n                          </o"
  "bject>\n                        </child>\n                        <chil"
  "d type=\"label\">\n                          <object class=\"GtkLabel\""
  " id=\"label10\">\n                            <property name=\"visible\""
  ">True</property>\n                            <property name=\"can_focu"
  "s\">False</property>\n                            <property name=\"even"
  "ts\">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTO"
  "N_PRESS_MASK | GDK_BUTTON_RELEASE_MASK</property>\n                    "
  "        <property name=\"label\" translatable=\"yes\">&lt;b&gt;Desktop "
  "Menu&lt;/b&gt;</property>\n                            <property name=\""
  "use_markup\">True</property>\n                          </object>\n    "
  "                    </child>\n                      </object>\n        "
  "              <packing>\n                        <property name=\"expan"
  "d\">False</property>\n                        <property name=\"fill\">T"
  "rue</property>\n                        <property name=\"position\">0</"
  "property>\n                      </packing>\n                    </chil"
  "d>\n                    <child>\n                      <object class=\""
  "GtkFrame\" id=\"frame5\">\n                        <property name=\"vis"
  "ible\">True</property>\n                        <property name=\"can_fo"
  "cus\">False</property>\n                        <property name=\"events"
  "\">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_"
  "PRESS_MASK | GDK_BUTTON_RELEASE_MASK</property>\n                      "
  "  <property name=\"label_xalign\">0</property>\n                       "
  " <property name=\"shadow_type\">none</property>\n                      "
  "  <child>\n                          <object class=\"GtkAlignment\" id="
  "\"alignment6\">\n                            <property name=\"visible\""
  ">True</property>\n                            <property name=\"can_focu"
  "s\">False</property>\n                            <property name=\"even"
  "ts\">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTO"
  "N_PRESS_MASK | GDK_BUTTON_RELEASE_MASK</property>\n                    "
  "        <property name=\"top_padding\">6</property>\n                  "
  "          <property name=\"left_padding\">12</property>\n              "
  "              <child>\n                              <object class=\"Gt"
  "kBox\" id=\"vbox8\">\n                                <property name=\""
  "visible\">True</property>\n                                <property na"
  "me=\"can_focus\">False</property>\n                                <pro"
  "perty name=\"events\">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT"
  "_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK</property>\n   "
  "                             <property name=\"orientation\">vertical</p"
  "roperty>\n                                <property name=\"spacing\">6<"
  "/property>\n                                <child>\n                  "
  "                <object class=\"GtkCheckButton\" id=\"chk_show_winlist_"
  "menu\">\n                                    <property name=\"label\" t"
  "ranslatable=\"yes\">Show _window list menu on desktop middle click</pro"
  "perty>\n                                    <property name=\"visible\">"
  "True</property>\n                                    <property name=\"c"
  "an_focus\">True</property>\n                                    <proper"
  "ty name=\"receives_default\">False</property>\n                        "
  "            <property name=\"events\">GDK_POINTER_MOTION_MASK | GDK_POI"
  "NTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK"
  "</property>\n                                    <property name=\"use_u"
  "nderline\">True</property>\n                                    <proper"
  "ty name=\"active\">True</property>\n                                   "
  " <property name=\"draw_indicator\">True</property>\n                   "
  "               </object>\n                                  <packing>\n"
  "                                    <property name=\"expand\">True</pro"
  "perty>\n                                    <property name=\"fill\">Tru"
  "e</property>\n                                    <property name=\"posi"
  "tion\">0</property>\n                                  </packing>\n    "
  "                            </child>\n                                <"
  "child>\n                                  <object class=\"GtkAlignment\""
  " id=\"box_winlist_subopts\">\n                                    <prop"
  "erty name=\"visible\">True</property>\n                                "
  "    <property name=\"can_focus\">False</property>\n                    "
  "                <property name=\"events\">GDK_POINTER_MOTION_MASK | GDK"
  "_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_"
  "MASK</property>\n                                    <property name=\"l"
  "eft_padding\">12</property>\n                                    <child"
  ">\n                                      <object class=\"GtkBox\" id=\""
  "vbox11\">\n                                        <property name=\"vis"
  "ible\">True</property>\n                                        <proper"
  "ty name=\"can_focus\">False</property>\n                               "
  "         <property name=\"events\">GDK_POINTER_MOTION_MASK | GDK_POINTE"
  "R_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK</p"
  "roperty>\n                                        <property name=\"orie"
  "ntation\">vertical</property>\n                                        "
  "<property name=\"spacing\">6</property>\n                              "
  "          <child>\n                                          <object cl"
  "ass=\"GtkBox\" id=\"hbox14\">\n                                        "
  "    <property name=\"can_focus\">False</property>\n                    "
  "                        <property name=\"events\">GDK_POINTER_MOTION_MA"
  "SK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_"
  "RELEASE_MASK</property>\n                                            <p"
  "roperty name=\"spacing\">12</property>\n                               "
  "             <child>\n                                              <ob"
  "ject class=\"GtkLabel\" id=\"label23\">\n                              "
  "                  <property name=\"visible\">True</property>\n         "
  "                                       <property name=\"can_focus\">Fal"
  "se</property>\n                                                <propert"
  "y name=\"events\">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MAS"
  "K | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK</property>\n       "
  "                                         <property name=\"label\" trans"
  "latable=\"yes\">B_utton:</property>\n                                  "
  "              <property name=\"use_underline\">True</property>\n       "
  "                                         <property name=\"mnemonic_widg"
  "et\">combobox8</property>\n                                            "
  "  </object>\n                                              <packing>\n "
  "                                               <property name=\"expand\""
  ">False</property>\n                                                <pro"
  "perty name=\"fill\">True</property>\n                                  "
  "              <property name=\"position\">0</property>\n               "
  "                               </packing>\n                            "
  "                </child>\n                                            <"
  "child>\n                                              <object class=\"G"
  "tkComboBox\" id=\"combobox8\">\n                                       "
  "         <property name=\"visible\">True</property>\n                  "
  "                              <property name=\"can_focus\">False</prope"
  "rty>\n                                                <property name=\""
  "events\">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_B"
  "UTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK</property>\n                "
  "                                <property name=\"model\">model5</proper"
  "ty>\n                                                <child>\n         "
  "                                         <object class=\"GtkCellRendere"
  "rText\" id=\"renderer5\"/>\n                                           "
  "       <attributes>\n                                                  "
  "  <attribute name=\"text\">0</attribute>\n                             "
  "                     </attributes>\n                                   "
  "             </child>\n                                              </"
  "object>\n                                              <packing>\n     "
  "                                           <property name=\"expand\">Fa"
  "lse</property>\n                                                <proper"
  "ty name=\"fill\">True</property>\n                                     "
  "           <property name=\"position\">1</property>\n                  "
  "                            </packing>\n                               "
  "             </child>\n                                            <chi"
  "ld>\n                                              <object class=\"GtkL"
  "abel\" id=\"label24\">\n                                               "
  " <property name=\"visible\">True</property>\n                          "
  "                      <property name=\"can_focus\">False</property>\n  "
  "                                              <property name=\"events\""
  ">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PR"
  "ESS_MASK | GDK_BUTTON_RELEASE_MASK</property>\n                        "
  "                        <property name=\"label\" translatable=\"yes\">M"
  "odi_fier:</property>\n                                                <"
  "property name=\"use_underline\">True</property>\n                      "
  "                          <property name=\"mnemonic_widget\">combobox9<"
  "/property>\n                                              </object>\n  "
  "                                            <packing>\n                "
  "                                <property name=\"expand\">False</proper"
  "ty>\n                                                <property name=\"f"
  "ill\">True</property>\n                                                "
  "<property name=\"position\">2</property>\n                             "
  "                 </packing>\n                                          "
  "  </child>\n                                            <child>\n      "
  "                                        <object class=\"GtkComboBox\" i"
  "d=\"combobox9\">\n                                                <prop"
  "erty name=\"visible\">True</property>\n                                "
  "                <property name=\"can_focus\">False</property>\n        "
  "                                        <property name=\"events\">GDK_P"
  "OINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MA"
  "SK | GDK_BUTTON_RELEASE_MASK</property>\n                              "
  "                  <property name=\"model\">model6</property>\n         "
  "                                       <child>\n                       "
  "                           <object class=\"GtkCellRendererText\" id=\"r"
  "enderer6\"/>\n                                                  <attrib"
  "utes>\n                                                    <attribute n"
  "ame=\"text\">0</attribute>\n                                           "
  "       </attributes>\n                                                <"
  "/child>\n                                              </object>\n     "
  "                                         <packing>\n                   "
  "                             <property name=\"expand\">False</property>"
  "\n                                                <property name=\"fill"
  "\">True</property>\n                                                <pr"
  "operty name=\"position\">3</property>\n                                "
  "              </packing>\n                                            <"
  "/child>\n                                          </object>\n         "
  "                                 <packing>\n                           "
  "                 <property name=\"expand\">True</property>\n           "
  "                                 <property name=\"fill\">True</property"
  ">\n                                            <property name=\"positio"
  "n\">0</property>\n                                          </packing>\n"
  "                                        </child>\n                     "
  "                   <child>\n                                          <"
  "object class=\"GtkCheckButton\" id=\"chk_winlist_show_app_icons\">\n   "
  "                                         <property name=\"label\" trans"
  "latable=\"yes\">Sh_ow application icons in menu</property>\n           "
  "                                 <property name=\"visible\">True</prope"
  "rty>\n                                            <property name=\"can_"
  "focus\">True</property>\n                                            <p"
  "roperty name=\"receives_default\">False</property>\n                   "
  "                         <property name=\"events\">GDK_POINTER_MOTION_M"
  "ASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON"
  "_RELEASE_MASK</property>\n                                            <"
  "property name=\"use_underline\">True</property>\n                      "
  "                      <property name=\"active\">True</property>\n      "
  "                                      <property name=\"draw_indicator\""
  ">True</property>\n                                          </object>\n"
  "                                          <packing>\n                  "
  "                          <property name=\"expand\">True</property>\n  "
  "                                          <property name=\"fill\">True<"
  "/property>\n                                            <property name="
  "\"position\">1</property>\n                                          </"
  "packing>\n                                        </child>\n           "
  "                             <child>\n                                 "
  "         <object class=\"GtkCheckButton\" id=\"chk_show_winlist_ws_name"
  "s\">\n                                            <property name=\"labe"
  "l\" translatable=\"yes\">Show workspace _names in list</property>\n    "
  "                                        <property name=\"visible\">True"
  "</property>\n                                            <property name"
  "=\"can_focus\">True</property>\n                                       "
  "     <property name=\"receives_default\">False</property>\n            "
  "                                <property name=\"events\">GDK_POINTER_M"
  "OTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK"
  "_BUTTON_RELEASE_MASK</property>\n                                      "
  "      <property name=\"use_underline\">True</property>\n               "
  "                             <property name=\"active\">True</property>\n"
  "                                            <property name=\"draw_indic"
  "ator\">True</property>\n                                          </obj"
  "ect>\n                                          <packing>\n            "
  "                                <property name=\"expand\">True</propert"
  "y>\n                                            <property name=\"fill\""
  ">True</property>\n                                            <property"
  " name=\"position\">2</property>\n                                      "
  "    </packing>\n                                        </child>\n     "
  "                                   <child>\n                           "
  "               <object class=\"GtkAlignment\" id=\"box_winlist_names_su"
  "bopts\">\n                                            <property name=\""
  "visible\">True</property>\n                                            "
  "<property name=\"can_focus\">False</property>\n                        "
  "                    <property name=\"events\">GDK_POINTER_MOTION_MASK |"
  " GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELE"
  "ASE_MASK</property>\n                                            <prope"
  "rty name=\"left_padding\">12</property>\n                              "
  "              <child>\n                                              <o"
  "bject class=\"GtkCheckButton\" id=\"chk_show_winlist_ws_submenus\">\n  "
  "                                              <property name=\"label\" "
  "translatable=\"yes\">Use _submenus for the windows in each workspace</p"
  "roperty>\n                                                <property nam"
  "e=\"visible\">True</property>\n                                        "
  "        <property name=\"can_focus\">True</property>\n                 "
  "                               <property name=\"receives_default\">Fals"
  "e</property>\n                                                <property"
  " name=\"events\">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK"
  " | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK</property>\n        "
  "                                        <property name=\"use_underline\""
  ">True</property>\n                                                <prop"
  "erty name=\"draw_indicator\">True</property>\n                         "
  "                     </object>\n                                       "
  "     </child>\n                                          </object>\n   "
  "                                       <packing>\n                     "
  "                       <property name=\"expand\">True</property>\n     "
  "                                       <property name=\"fill\">True</pr"
  "operty>\n                                            <property name=\"p"
  "osition\">3</property>\n                                          </pac"
  "king>\n                                        </child>\n              "
  "                          <child>\n                                    "
  "      <object class=\"GtkCheckButton\" id=\"chk_show_winlist_sticky_onc"
  "e\">\n                                            <property name=\"labe"
  "l\" translatable=\"yes\">Show s_ticky windows only in active workspace<"
  "/property>\n                                            <property name="
  "\"visible\">True</property>\n                                          "
  "  <property name=\"can_focus\">True</property>\n                       "
  "                     <property name=\"receives_default\">False</propert"
  "y>\n                                            <property name=\"events"
  "\">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_"
  "PRESS_MASK | GDK_BUTTON_RELEASE_MASK</property>\n                      "
  "                      <property name=\"use_underline\">True</property>\n"
  "                                            <property name=\"draw_indic"
  "ator\">True</property>\n                                          </obj"
  "ect>\n                                          <packing>\n            "
  "                                <property name=\"expand\">True</propert"
  "y>\n                                            <property name=\"fill\""
  ">True</property>\n                                            <property"
  " name=\"position\">4</property>\n                                      "
  "    </packing>\n                                        </child>\n     "
  "                                   <child>\n                           "
  "               <object class=\"GtkCheckButton\" id=\"chk_show_app_remov"
  "e_workspaces\">\n                                            <property "
  "name=\"label\" translatable=\"yes\">Show a_dd and remove workspace opti"
  "ons in list</property>\n                                            <pr"
  "operty name=\"visible\">True</property>\n                              "
  "              <property name=\"can_focus\">True</property>\n           "
  "                                 <property name=\"receives_default\">Fa"
  "lse</property>\n                                            <property n"
  "ame=\"events\">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK |"
  " GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK</property>\n          "
  "                                  <property name=\"use_underline\">True"
  "</property>\n                                            <property name"
  "=\"active\">True</property>\n                                          "
  "  <property name=\"draw_indicator\">True</property>\n                  "
  "                        </object>\n                                    "
  "      <packing>\n                                            <property "
  "name=\"expand\">True</property>\n                                      "
  "      <property name=\"fill\">True</property>\n                        "
  "                    <property name=\"position\">5</property>\n         "
  "                                 </packing>\n                          "
  "              </child>\n                                      </object>"
  "\n                                    </child>\n                       "
  "           </object>\n                                  <packing>\n    "
  "                                <property name=\"expand\">True</propert"
  "y>\n                                    <property name=\"fill\">True</p"
  "roperty>\n                                    <property name=\"position"
  "\">1</property>\n                                  </packing>\n        "
  "                        </child>\n                              </objec"
  "t>\n                            </child>\n                          </o"
  "bject>\n                        </child>\n                        <chil"
  "d type=\"label\">\n                          <object class=\"GtkLabel\""
  " id=\"label11\">\n                            <property name=\"visible\""
  ">True</property>\n                            <property name=\"can_focu"
  "s\">False</property>\n                            <property name=\"even"
  "ts\">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTO"
  "N_PRESS_MASK | GDK_BUTTON_RELEASE_MASK</property>\n                    "
  "        <property name=\"label\" translatable=\"yes\">&lt;b&gt;Window L"
  "ist Menu&lt;/b&gt;</property>\n                            <property na"
  "me=\"use_markup\">True</property>\n                          </object>\n"
  "                        </child>\n                      </object>\n    "
  "                  <packing>\n                        <property name=\"e"
  "xpand\">False</property>\n                        <property name=\"fill"
  "\">True</property>\n                        <property name=\"position\""
  ">1</property>\n                      </packing>\n                    </"
  "child>\n                  </object>\n                  <packing>\n     "
  "               <property name=\"position\">1</property>\n              "
  "    </packing>\n                </child>\n                <child type=\""
  "tab\">\n                  <object class=\"GtkLabel\" id=\"label2\">\n  "
  "                  <property name=\"visible\">True</property>\n         "
  "           <property name=\"can_focus\">False</property>\n             "
  "       <property name=\"events\">GDK_POINTER_MOTION_MASK | GDK_POINTER_"
  "MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK</pro"
  "perty>\n                    <property name=\"label\" translatable=\"yes"
  "\">_Menus</property>\n                    <property name=\"use_underlin"
  "e\">True</property>\n                  </object>\n                  <pa"
  "cking>\n                    <property name=\"position\">1</property>\n "
  "                   <property name=\"tab_fill\">False</property>\n      "
  "            </packing>\n                </child>\n                <chil"
  "d>\n                  <object class=\"GtkBox\" id=\"vbox9\">\n         "
  "           <property name=\"visible\">True</property>\n                "
  "    <property name=\"can_focus\">False</property>\n                    "
  "<property name=\"events\">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_"
  "HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK</property>\n"
  "                    <property name=\"border_width\">12</property>\n    "
  "                <property name=\"orientation\">vertical</property>\n   "
  "                 <property name=\"spacing\">18</property>\n            "
  "        <child>\n                      <object class=\"GtkFrame\" id=\""
  "frame6\">\n                        <property name=\"visible\">True</pro"
  "perty>\n                        <property name=\"can_focus\">False</pro"
  "perty>\n                        <property name=\"events\">GDK_POINTER_M"
  "OTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK"
  "_BUTTON_RELEASE_MASK</property>\n                        <property name"
  "=\"label_xalign\">0</property>\n                        <property name="
  "\"shadow_type\">none</property>\n                        <child>\n     "
  "                     <object class=\"GtkAlignment\" id=\"alignment11\">"
  "\n                            <property name=\"visible\">True</property"
  ">\n                            <property name=\"can_focus\">False</prop"
  "erty>\n                            <property name=\"events\">GDK_POINTE"
  "R_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK | "
  "GDK_BUTTON_RELEASE_MASK</property>\n                            <proper"
  "ty name=\"top_padding\">6</property>\n                            <prop"
  "erty name=\"left_padding\">12</property>\n                            <"
  "child>\n                              <object class=\"GtkGrid\">\n     "
  "                           <property name=\"visible\">True</property>\n"
  "                                <property name=\"can_focus\">False</pro"
  "perty>\n                                <property name=\"row_spacing\">"
  "6</property>\n                                <property name=\"column_s"
  "pacing\">12</property>\n                                <child>\n      "
  "                            <object class=\"GtkLabel\" id=\"label12\">\n"
  "                                    <property name=\"visible\">True</pr"
  "operty>\n                                    <property name=\"can_focus"
  "\">False</property>\n                                    <property name"
  "=\"events\">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GD"
  "K_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK</property>\n             "
  "                       <property name=\"label\" translatable=\"yes\">Ic"
  "on _type:</property>\n                                    <property nam"
  "e=\"use_underline\">True</property>\n                                  "
  "  <property name=\"xalign\">0</property>\n                             "
  "     </object>\n                                  <packing>\n          "
  "                          <property name=\"left_attach\">0</property>\n"
  "                                    <property name=\"top_attach\">0</pr"
  "operty>\n                                  </packing>\n                "
  "                </child>\n                                <child>\n    "
  "                              <object class=\"GtkComboBox\" id=\"combo_"
  "icons\">\n                                    <property name=\"visible\""
  ">True</property>\n                                    <property name=\""
  "can_focus\">False</property>\n                                    <prop"
  "erty name=\"events\">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_"
  "MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK</property>\n    "
  "                                <property name=\"halign\">start</proper"
  "ty>\n                                    <property name=\"model\">model"
  "7</property>\n                                    <child>\n            "
  "                          <object class=\"GtkCellRendererText\" id=\"re"
  "nderer7\"/>\n                                      <attributes>\n      "
  "                                  <attribute name=\"text\">0</attribute"
  ">\n                                      </attributes>\n               "
  "                     </child>\n                                  </obje"
  "ct>\n                                  <packing>\n                     "
  "               <property name=\"left_attach\">1</property>\n           "
  "                         <property name=\"top_attach\">0</property>\n  "
  "                                </packing>\n                           "
  "     </child>\n                                <child>\n               "
  "                   <object class=\"GtkLabel\" id=\"label13\">\n        "
  "                            <property name=\"visible\">True</property>\n"
  "                                    <property name=\"can_focus\">False<"
  "/property>\n                                    <property name=\"events"
  "\">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_"
  "PRESS_MASK | GDK_BUTTON_RELEASE_MASK</property>\n                      "
  "              <property name=\"label\" translatable=\"yes\">Icon _size:"
  "</property>\n                                    <property name=\"use_u"
  "nderline\">True</property>\n                                    <proper"
  "ty name=\"xalign\">0</property>\n                                  </ob"
  "ject>\n                                  <packing>\n                   "
  "                 <property name=\"left_attach\">0</property>\n         "
  "                           <property name=\"top_attach\">1</property>\n"
  "                                  </packing>\n                         "
  "       </child>\n                                <child>\n             "
  "                     <object class=\"GtkSpinButton\" id=\"spin_icon_siz"
  "e\">\n                                    <property name=\"visible\">Tr"
  "ue</property>\n                                    <property name=\"can"
  "_focus\">True</property>\n                                    <property"
  " name=\"events\">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK"
  " | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK</property>\n        "
  "                            <property name=\"halign\">start</property>\n"
  "                                    <property name=\"text\" translatabl"
  "e=\"yes\">48</property>\n                                    <property "
  "name=\"adjustment\">adjustment3</property>\n                           "
  "         <property name=\"value\">48</property>\n                      "
  "            </object>\n                                  <packing>\n   "
  "                                 <property name=\"left_attach\">1</prop"
  "erty>\n                                    <property name=\"top_attach\""
  ">1</property>\n                                  </packing>\n          "
  "                      </child>\n                                <child>"
  "\n                                  <object class=\"GtkLabel\" id=\"lab"
  "el14\">\n                                    <property name=\"visible\""
  ">True</property>\n                                    <property name=\""
  "can_focus\">False</property>\n                                    <prop"
  "erty name=\"events\">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_"
  "MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK</property>\n    "
  "                                <property name=\"label\" translatable=\""
  "yes\">Icons _orientation:</property>\n                                 "
  "   <property name=\"use_underline\">True</property>\n                  "
  "                  <property name=\"xalign\">0</property>\n             "
  "                     </object>\n                                  <pack"
  "ing>\n                                    <property name=\"left_attach\""
  ">0</property>\n                                    <property name=\"top"
  "_attach\">2</property>\n                                  </packing>\n "
  "                               </child>\n                              "
  "  <child>\n                                  <object class=\"GtkComboBo"
  "x\" id=\"combo_orientation\">\n                                    <pro"
  "perty name=\"visible\">True</property>\n                               "
  "     <property name=\"can_focus\">False</property>\n                   "
  "                 <property name=\"events\">GDK_POINTER_MOTION_MASK | GD"
  "K_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE"
  "_MASK</property>\n                                    <property name=\""
  "halign\">start</property>\n                                    <propert"
  "y name=\"model\">model8</property>\n                                   "
  " <child>\n                                      <object class=\"GtkCell"
  "RendererText\" id=\"renderer8\"/>\n                                    "
  "  <attributes>\n                                        <attribute name"
  "=\"text\">0</attribute>\n                                      </attrib"
  "utes>\n                                    </child>\n                  "
  "                </object>\n                                  <packing>\n"
  "                                    <property name=\"left_attach\">1</p"
  "roperty>\n                                    <property name=\"top_atta"
  "ch\">2</property>\n                                  </packing>\n      "
  "                          </child>\n                                <ch"
  "ild>\n                                  <object class=\"GtkCheckButton\""
  " id=\"primary\">\n                                    <property name=\""
  "label\" translatable=\"yes\">Show icons on primary display</property>\n"
  "                                    <property name=\"visible\">True</pr"
  "operty>\n                                    <property name=\"can_focus"
  "\">True</property>\n                                    <property name="
  "\"receives_default\">False</property>\n                                "
  "    <property name=\"draw_indicator\">True</property>\n                "
  "                  </object>\n                                  <packing"
  ">\n                                    <property name=\"left_attach\">0"
  "</property>\n                                    <property name=\"top_a"
  "ttach\">3</property>\n                                  </packing>\n   "
  "                             </child>\n                                "
  "<child>\n                                  <object class=\"GtkCheckButt"
  "on\" id=\"chk_custom_font_size\">\n                                    "
  "<property name=\"label\" translatable=\"yes\">Use custom _font size:</p"
  "roperty>\n                                    <property name=\"visible\""
  ">True</property>\n                                    <property name=\""
  "can_focus\">True</property>\n                                    <prope"
  "rty name=\"receives_default\">False</property>\n                       "
  "             <property name=\"events\">GDK_POINTER_MOTION_MASK | GDK_PO"
  "INTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MAS"
  "K</property>\n                                    <property name=\"use_"
  "underline\">True</property>\n                                    <prope"
  "rty name=\"draw_indicator\">True</property>\n                          "
  "        </object>\n                                  <packing>\n       "
  "                             <property name=\"left_attach\">0</property"
  ">\n                                    <property name=\"top_attach\">4<"
  "/property>\n                                  </packing>\n             "
  "                   </child>\n                                <child>\n "
  "                                 <object class=\"GtkSpinButton\" id=\"s"
  "pin_font_size\">\n                                    <property name=\""
  "visible\">True</property>\n                                    <propert"
  "y name=\"sensitive\">False</property>\n                                "
  "    <property name=\"can_focus\">True</property>\n                     "
  "               <property name=\"events\">GDK_POINTER_MOTION_MASK | GDK_"
  "POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_M"
  "ASK</property>\n                                    <property name=\"ha"
  "lign\">start</property>\n                                    <property "
  "name=\"text\" translatable=\"yes\">12</property>\n                     "
  "               <property name=\"adjustment\">adjustment4</property>\n  "
  "                                  <property name=\"value\">12</property"
  ">\n                                  </object>\n                       "
  "           <packing>\n                                    <property nam"
  "e=\"left_attach\">1</property>\n                                    <pr"
  "operty name=\"top_attach\">4</property>\n                              "
  "    </packing>\n                                </child>\n             "
  "                   <child>\n                                  <object c"
  "lass=\"GtkCheckButton\" id=\"chk_show_tooltips\">\n                    "
  "                <property name=\"label\" translatable=\"yes\">Show icon"
  " tooltips. Size:</property>\n                                    <prope"
  "rty name=\"visible\">True</property>\n                                 "
  "   <property name=\"can_focus\">True</property>\n                      "
  "              <property name=\"receives_default\">False</property>\n   "
  "                                 <property name=\"events\">GDK_POINTER_"
  "MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK | GD"
  "K_BUTTON_RELEASE_MASK</property>\n                                    <"
  "property name=\"use_underline\">True</property>\n                      "
  "              <property name=\"active\">True</property>\n              "
  "                      <property name=\"draw_indicator\">True</property>"
  "\n                                  </object>\n                        "
  "          <packing>\n                                    <property name"
  "=\"left_attach\">0</property>\n                                    <pro"
  "perty name=\"top_attach\">5</property>\n                               "
  "   </packing>\n                                </child>\n              "
  "                  <child>\n                                  <object cl"
  "ass=\"GtkSpinButton\" id=\"spin_tooltip_size\">\n                      "
  "              <property name=\"visible\">True</property>\n             "
  "                       <property name=\"can_focus\">True</property>\n  "
  "                                  <property name=\"events\">GDK_POINTER"
  "_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK | G"
  "DK_BUTTON_RELEASE_MASK</property>\n                                    "
  "<property name=\"tooltip_text\" translatable=\"yes\">Size of the toolti"
  "p preview image.</property>\n                                    <prope"
  "rty name=\"halign\">start</property>\n                                 "
  "   <property name=\"text\" translatable=\"yes\">128</property>\n       "
  "                             <property name=\"adjustment\">adjustment_t"
  "ooltip</property>\n                                    <property name=\""
  "value\">128</property>\n                                  </object>\n  "
  "                                <packing>\n                            "
  "        <property name=\"left_attach\">1</property>\n                  "
  "                  <property name=\"top_attach\">5</property>\n         "
  "                         </packing>\n                                </"
  "child>\n                                <child>\n                      "
  "            <object class=\"GtkCheckButton\" id=\"chk_show_thumbnails\""
  ">\n                                    <property name=\"label\" transla"
  "table=\"yes\">Show t_humbnails</property>\n                            "
  "        <property name=\"visible\">True</property>\n                   "
  "                 <property name=\"can_focus\">True</property>\n        "
  "                            <property name=\"receives_default\">False</"
  "property>\n                                    <property name=\"events\""
  ">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PR"
  "ESS_MASK | GDK_BUTTON_RELEASE_MASK</property>\n                        "
  "            <property name=\"tooltip_text\" translatable=\"yes\">Select"
  " this option to display preview-able files on the desktop as automatica"
  "lly generated thumbnail icons.</property>\n                            "
  "        <property name=\"use_underline\">True</property>\n             "
  "                       <property name=\"draw_indicator\">True</property"
  ">\n                                  </object>\n                       "
  "           <packing>\n                                    <property nam"
  "e=\"left_attach\">0</property>\n                                    <pr"
  "operty name=\"top_attach\">6</property>\n                              "
  "    </packing>\n                                </child>\n             "
  "                   <child>\n                                  <object c"
  "lass=\"GtkCheckButton\" id=\"chk_show_hidden_files\">\n                "
  "                    <property name=\"label\" translatable=\"yes\">Show "
  "hidden files on the desktop</property>\n                               "
  "     <property name=\"visible\">True</property>\n                      "
  "              <property name=\"can_focus\">True</property>\n           "
  "                         <property name=\"receives_default\">False</pro"
  "perty>\n                                    <property name=\"events\">G"
  "DK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRES"
  "S_MASK | GDK_BUTTON_RELEASE_MASK</property>\n                          "
  "          <property name=\"use_underline\">True</property>\n           "
  "                         <property name=\"draw_indicator\">True</proper"
  "ty>\n                                  </object>\n                     "
  "             <packing>\n                                    <property n"
  "ame=\"left_attach\">0</property>\n                                    <"
  "property name=\"top_attach\">7</property>\n                            "
  "      </packing>\n                                </child>\n           "
  "                     <child>\n                                  <object"
  " class=\"GtkCheckButton\" id=\"chk_single_click\">\n                   "
  "                 <property name=\"label\" translatable=\"yes\">Single _"
  "click to activate items</property>\n                                   "
  " <property name=\"visible\">True</property>\n                          "
  "          <property name=\"can_focus\">True</property>\n               "
  "                     <property name=\"receives_default\">False</propert"
  "y>\n                                    <property name=\"events\">GDK_P"
  "OINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MA"
  "SK | GDK_BUTTON_RELEASE_MASK</property>\n                              "
  "      <property name=\"use_underline\">True</property>\n               "
  "                     <property name=\"draw_indicator\">True</property>\n"
  "                                  </object>\n                          "
  "        <packing>\n                                    <property name=\""
  "left_attach\">0</property>\n                                    <proper"
  "ty name=\"top_attach\">8</property>\n                                  "
  "</packing>\n                                </child>\n                 "
  "               <child>\n                                  <placeholder/"
  ">\n                                </child>\n                          "
  "      <child>\n                                  <placeholder/>\n      "
  "                          </child>\n                                <ch"
  "ild>\n                                  <placeholder/>\n               "
  "                 </child>\n                                <child>\n   "
  "                               <placeholder/>\n                        "
  "        </child>\n                              </object>\n            "
  "                </child>\n                          </object>\n        "
  "                </child>\n                        <child type=\"label\""
  ">\n                          <object class=\"GtkLabel\" id=\"label15\">"
  "\n                            <property name=\"visible\">True</property"
  ">\n                            <property name=\"can_focus\">False</prop"
  "erty>\n                            <property name=\"events\">GDK_POINTE"
  "R_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK | "
  "GDK_BUTTON_RELEASE_MASK</property>\n                            <proper"
  "ty name=\"label\" translatable=\"yes\">&lt;b&gt;Appearance&lt;/b&gt;</p"
  "roperty>\n                            <property name=\"use_markup\">Tru"
  "e</property>\n                          </object>\n                    "
  "    </child>\n                      </object>\n                      <p"
  "acking>\n                        <property name=\"expand\">False</prope"
  "rty>\n                        <property name=\"fill\">True</property>\n"
  "                        <property name=\"position\">0</property>\n     "
  "                 </packing>\n                    </child>\n            "
  "        <child>\n                      <object class=\"GtkFrame\" id=\""
  "frame7\">\n                        <property name=\"visible\">True</pro"
  "perty>\n                        <property name=\"can_focus\">False</pro"
  "perty>\n                        <property name=\"events\">GDK_POINTER_M"
  "OTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK"
  "_BUTTON_RELEASE_MASK</property>\n                        <property name"
  "=\"label_xalign\">0</property>\n                        <property name="
  "\"shadow_type\">none</property>\n                        <child>\n     "
  "                     <object class=\"GtkAlignment\" id=\"alignment12\">"
  "\n                            <property name=\"visible\">True</property"
  ">\n                            <property name=\"can_focus\">False</prop"
  "erty>\n                            <property name=\"events\">GDK_POINTE"
  "R_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK | "
  "GDK_BUTTON_RELEASE_MASK</property>\n                            <proper"
  "ty name=\"top_padding\">6</property>\n                            <prop"
  "erty name=\"left_padding\">12</property>\n                            <"
  "child>\n                              <object class=\"GtkScrolledWindow"
  "\" id=\"scrolledwindow2\">\n                                <property n"
  "ame=\"visible\">True</property>\n                                <prope"
  "rty name=\"can_focus\">True</property>\n                               "
  " <property name=\"events\">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION"
  "_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK</property>"
  "\n                                <property name=\"shadow_type\">etched"
  "-in</property>\n                                <child>\n              "
  "                    <object class=\"GtkTreeView\" id=\"treeview_default"
  "_icons\">\n                                    <property name=\"visible"
  "\">True</property>\n                                    <property name="
  "\"can_focus\">True</property>\n                                    <pro"
  "perty name=\"events\">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT"
  "_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK</property>\n   "
  "                                 <property name=\"headers_visible\">Fal"
  "se</property>\n                                    <child internal-chil"
  "d=\"selection\">\n                                      <object class=\""
  "GtkTreeSelection\"/>\n                                    </child>\n   "
  "                               </object>\n                             "
  "   </child>\n                              </object>\n                 "
  "           </child>\n                          </object>\n             "
  "           </child>\n                        <child type=\"label\">\n  "
  "                        <object class=\"GtkLabel\" id=\"label16\">\n   "
  "                         <property name=\"visible\">True</property>\n  "
  "                          <property name=\"can_focus\">False</property>"
  "\n                            <property name=\"events\">GDK_POINTER_MOT"
  "ION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK_B"
  "UTTON_RELEASE_MASK</property>\n                            <property na"
  "me=\"label\" translatable=\"yes\">&lt;b&gt;Default Icons&lt;/b&gt;</pro"
  "perty>\n                            <property name=\"use_markup\">True<"
  "/property>\n                          </object>\n                      "
  "  </child>\n                      </object>\n                      <pac"
  "king>\n                        <property name=\"expand\">True</property"
  ">\n                        <property name=\"fill\">True</property>\n   "
  "                     <property name=\"position\">1</property>\n        "
  "              </packing>\n                    </child>\n               "
  "   </object>\n                  <packing>\n                    <propert"
  "y name=\"position\">2</property>\n                  </packing>\n       "
  "         </child>\n                <child type=\"tab\">\n              "
  "    <object class=\"GtkLabel\" id=\"label3\">\n                    <pro"
  "perty name=\"visible\">True</property>\n                    <property n"
  "ame=\"can_focus\">False</property>\n                    <property name="
  "\"events\">GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK"
  "_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK</property>\n              "
  "      <property name=\"label\" translatable=\"yes\">_Icons</property>\n"
  "                    <property name=\"use_underline\">True</property>\n "
  "                 </object>\n                  <packing>\n              "
  "      <property name=\"position\">2</property>\n                    <pr"
  "operty name=\"tab_fill\">False</property>\n                  </packing>"
  "\n                </child>\n              </object>\n            </chil"
  "d>\n          </object>\n          <packing>\n            <property nam"
  "e=\"expand\">False</property>\n            <property name=\"fill\">True"
  "</property>\n            <property name=\"position\">1</property>\n    "
  "      </packing>\n        </child>\n      </object>\n    </child>\n    "
  "<action-widgets>\n      <action-widget response=\"-11\">button2</action"
  "-widget>\n      <action-widget response=\"-3\">bnt_exit</action-widget>"
  "\n    </action-widgets>\n  </object>\n</interface>\n"
};

static const unsigned xfdesktop_settings_ui_length = 72210u;

